### PR TITLE
lay the ground for item3

### PR DESCRIPTION
**Pull request by venam**
This sets a todo list for what to fill in this section

### CODE REVIEW

**Comment by venam** [comment]
Same as with item4, this should start the discussion about the topic and make it easy to fill up.

**Comment by feroldi** [comment]
Sorry, I missed this PR. Should this be merged?

**Comment by venam** [comment]
If you have no issue with the points I've listed then yes.

**Comment by feroldi** [comment]
I think you have enough privileges to merge PRs. Don't hesitate on that!

**Pull request merged**
